-- Database: management-of-employees

-- DROP DATABASE IF EXISTS "management-of-employees";
/*
CREATE DATABASE "management-of-employees"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_United States.1252'
    LC_CTYPE = 'English_United States.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
*/

DROP TABLE IF EXISTS EMPLOYEES;

CREATE TABLE EMPLOYEES (
	ID				SERIAL			PRIMARY KEY,
	FIRST_NAME		VARCHAR(40) 	NOT NULL,
	SECOND_NAME 	VARCHAR(40),
	FIRST_SURNAME	VARCHAR(40)		NOT NULL,
	SECOND_SURNAME	VARCHAR(40)		NOT NULL,
	AGE				INT				NOT NULL,
	GENDER			CHAR(1)			NOT NULL CHECK (GENDER IN ('M', 'F')),
	DATE_OF_BIRTH	DATE			NOT NULL,
	POSITION		VARCHAR(200)	NOT NULL
);

INSERT INTO EMPLOYEES (FIRST_NAME, SECOND_NAME, FIRST_SURNAME, SECOND_SURNAME, AGE, GENDER, DATE_OF_BIRTH, POSITION) 
	VALUES 
		('PEDRO', 'JOSE', 'ALCANTARA', 'CARMONA', 45, 'M', '1980-06-12', 'CONTADOR'),
		('JOSE', NULL, 'ALCANTARA', 'CARMONA', 31, 'M', '1993-01-24', 'GERENTE'),
		('MARIA', 'DEL CARMEN', 'HERNANDEZ', 'GARCIA', 25, 'F', '2000-11-05', 'SISTEMAS');


SELECT * FROM EMPLOYEES;